"use strict";

// TRIPEASE - BOOKING DATA
// Hotels, Flights, Trains & Buses

// 1. HOTEL DATA

const hotels = [
  {
    id: 1,
    name: "The Taj Palace",
    city: "Delhi",
    location: "New Delhi",
    rating: 4.8,
    reviews: 2450,
    price: 8500,
    badge: "Luxury Stay",
    amenities: ["WiFi", "Pool", "Restaurant", "AC"],
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
  },
  {
    id: 2,
    name: "The Oberoi",
    city: "Mumbai",
    location: "Marine Drive",
    rating: 4.9,
    reviews: 3200,
    price: 12000,
    badge: "Premium",
    amenities: ["WiFi", "Pool", "Spa", "AC"],
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
  },
  {
    id: 3,
    name: "Mountain View Resort",
    city: "Manali",
    location: "Old Manali",
    rating: 4.6,
    reviews: 980,
    price: 4500,
    badge: "Mountain View",
    amenities: ["WiFi", "Parking", "Restaurant"],
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800",
  },
  {
    id: 4,
    name: "Goa Beach Resort",
    city: "Goa",
    location: "Baga Beach",
    rating: 4.7,
    reviews: 1850,
    price: 6500,
    badge: "Beachfront",
    amenities: ["WiFi", "Pool", "Beach Access"],
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
  },
  {
    id: 5,
    name: "Lake Palace Hotel",
    city: "Udaipur",
    location: "Lake Pichola",
    rating: 4.9,
    reviews: 2100,
    price: 15000,
    badge: "Heritage",
    amenities: ["WiFi", "Restaurant", "Lake View"],
    image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800",
  },
  {
    id: 6,
    name: "Himalayan Retreat",
    city: "Shimla",
    location: "Mall Road",
    rating: 4.5,
    reviews: 760,
    price: 3800,
    badge: "Popular",
    amenities: ["WiFi", "Parking", "Mountain View"],
    image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800",
  },
  {
    id: 7,
    name: "Backwater Paradise",
    city: "Munnar",
    location: "Tea Garden Road",
    rating: 4.6,
    reviews: 890,
    price: 5200,
    badge: "Nature Stay",
    amenities: ["WiFi", "Restaurant", "Garden"],
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800",
  },
  {
    id: 8,
    name: "Royal Heritage Inn",
    city: "Jaipur",
    location: "Pink City",
    rating: 4.7,
    reviews: 1450,
    price: 5800,
    badge: "Heritage",
    amenities: ["WiFi", "Pool", "Restaurant"],
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800",
  },
  {
    id: 9,
    name: "Valley View Hotel",
    city: "Nainital",
    location: "Mallital",
    rating: 4.4,
    reviews: 620,
    price: 3200,
    badge: "Budget Friendly",
    amenities: ["WiFi", "Parking", "Lake View"],
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800",
  },
  {
    id: 10,
    name: "The Grand Varanasi",
    city: "Varanasi",
    location: "Assi Ghat",
    rating: 4.5,
    reviews: 1100,
    price: 4200,
    badge: "City Stay",
    amenities: ["WiFi", "Restaurant", "AC"],
    image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800",
  },
];

// 2. FLIGHT DATA

const flights = [
  {
    id: 1,
    name: "IndiGo",
    airline: "IndiGo",
    flightNumber: "6E-201",
    from: "Delhi",
    to: "Mumbai",
    departure: "06:00",
    arrival: "08:10",
    duration: "2h 10m",
    price: 4500,
    type: "Non-stop",
    class: "Economy",
    badge: "Popular",
    image:
      "https://www.hindustantimes.com/ht-img/img/2026/07/08/cropped/16-9/An-IndiGo-flight-lands-at-the-Noida-International-_1783473243496_1783473275782_b9d67fb5-94ff-4b85-8145-837306dccdaf.jpg",
  },
  {
    id: 2,
    name: "Air India",
    airline: "Air India",
    flightNumber: "AI-405",
    from: "Delhi",
    to: "Bengaluru",
    departure: "09:30",
    arrival: "12:20",
    duration: "2h 50m",
    price: 6200,
    type: "Non-stop",
    class: "Economy",
    badge: "Comfort",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvGQwEbsTWi46lUbc_WABwZhRgP89q93sj2ujkd14XMUos8XiS3jdwbxI&s=10",
  },
  {
    id: 3,
    name: "Akasa Air",
    airline: "Akasa Air",
    flightNumber: "QP-112",
    from: "Mumbai",
    to: "Goa",
    departure: "07:15",
    arrival: "08:25",
    duration: "1h 10m",
    price: 3200,
    type: "Non-stop",
    class: "Economy",
    badge: "Best Price",
    image:
      "https://a.storyblok.com/f/159922/3000x1688/fd58f43a36/rp_image.webp",
  },
  {
    id: 4,
    name: "SpiceJet",
    airline: "SpiceJet",
    flightNumber: "SG-819",
    from: "Delhi",
    to: "Jaipur",
    departure: "11:00",
    arrival: "12:00",
    duration: "1h",
    price: 2800,
    type: "Non-stop",
    class: "Economy",
    badge: "Budget",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmRY4sg2n9Lrs0ZLz9kJbJFHWC7Dq18W-LsPqQL7tZUw&s=10",
  },
  {
    id: 5,
    name: "IndiGo",
    airline: "IndiGo",
    flightNumber: "6E-502",
    from: "Bengaluru",
    to: "Chennai",
    departure: "14:30",
    arrival: "15:35",
    duration: "1h 5m",
    price: 2900,
    type: "Non-stop",
    class: "Economy",
    badge: "Popular",
    image:
      "https://static.toiimg.com/thumb/msid-100468509,width-1280,height-720,resizemode-4/100468509.jpg",
  },
  {
    id: 6,
    name: "Vistara",
    airline: "Air India",
    flightNumber: "AI-712",
    from: "Mumbai",
    to: "Kolkata",
    departure: "16:00",
    arrival: "18:45",
    duration: "2h 45m",
    price: 7100,
    type: "Non-stop",
    class: "Economy",
    badge: "Comfort",
    image:
      "https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2024/07/29104503/vistara-1600x900.jpg",
  },
  {
    id: 7,
    name: "IndiGo",
    airline: "IndiGo",
    flightNumber: "6E-340",
    from: "Lucknow",
    to: "Delhi",
    departure: "08:20",
    arrival: "09:35",
    duration: "1h 15m",
    price: 3500,
    type: "Non-stop",
    class: "Economy",
    badge: "Popular",
    image:
      "https://www.siasat.com/wp-content/uploads/2023/06/indigo-780x470.jpg",
  },
  {
    id: 8,
    name: "Akasa Air",
    airline: "Akasa Air",
    flightNumber: "QP-225",
    from: "Pune",
    to: "Bengaluru",
    departure: "18:10",
    arrival: "19:35",
    duration: "1h 25m",
    price: 3800,
    type: "Non-stop",
    class: "Economy",
    badge: "Best Price",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDXpZ9AGxAuokhuZYpPjC3L2JDWNLS3rYlCsNI8jyEIoDXWA8gK5GDijEp&s=10",
  },
  {
    id: 9,
    name: "SpiceJet",
    airline: "SpiceJet",
    flightNumber: "SG-610",
    from: "Delhi",
    to: "Goa",
    departure: "05:45",
    arrival: "08:20",
    duration: "2h 35m",
    price: 5400,
    type: "Non-stop",
    class: "Economy",
    badge: "Popular",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAhi_3pSJ4L82df_Wm8Z6Ji9nBdxGQU6xtimRpcYqDlLqW9Q-n6BNznho&s=10",
  },
  {
    id: 10,
    name: "Air India",
    airline: "Air India",
    flightNumber: "AI-305",
    from: "Hyderabad",
    to: "Mumbai",
    departure: "20:00",
    arrival: "21:30",
    duration: "1h 30m",
    price: 4200,
    type: "Non-stop",
    class: "Economy",
    badge: "Comfort",
    image:
      "https://media.assettype.com/outlooktraveller/2025-06-17/xcnlxl0r/shutterstock2538615397-min.jpg?w=640",
  },
];

// 3. TRAIN DATA

const trains = [
  {
    id: 1,
    name: "Rajdhani Express",
    trainNumber: "12951",
    from: "Mumbai",
    to: "Delhi",
    departure: "16:35",
    arrival: "08:30",
    duration: "15h 55m",
    price: 2450,
    type: "Superfast",
    class: "3A",
    badge: "Premium",
    image:
      "https://i.ndtvimg.com/i/2017-08/rajdhani-express_650x400_61502874271.jpg",
  },
  {
    id: 2,
    name: "Shatabdi Express",
    trainNumber: "12002",
    from: "New Delhi",
    to: "Bhopal",
    departure: "06:00",
    arrival: "14:25",
    duration: "8h 25m",
    price: 1850,
    type: "Superfast",
    class: "CC",
    badge: "Popular",
    image:
      "https://tajmahalcabs.com/wp-content/uploads/Shatabdi-Express-Train-2.jpg",
  },
  {
    id: 3,
    name: "Duronto Express",
    trainNumber: "12213",
    from: "Bengaluru",
    to: "Delhi",
    departure: "23:00",
    arrival: "05:45",
    duration: "30h 45m",
    price: 2800,
    type: "Express",
    class: "3A",
    badge: "Comfort",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuAUqPTa1tuhxxrRQqY5J1u5LyWLF2WeNyjXUQIh0cAE58-icz6mUB-gw&s=10",
  },
  {
    id: 4,
    name: "Vande Bharat Express",
    trainNumber: "22436",
    from: "New Delhi",
    to: "Varanasi",
    departure: "06:00",
    arrival: "14:00",
    duration: "8h",
    price: 1800,
    type: "Semi High-Speed",
    class: "CC",
    badge: "Fast",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRErufQTdPY3VtxOjmlKHbJm22T8ZTW1XaL7AyZJhuGgu8gUUWikI-TwVo&s=10",
  },
  {
    id: 5,
    name: "Gatimaan Express",
    trainNumber: "12050",
    from: "Delhi",
    to: "Agra",
    departure: "08:10",
    arrival: "09:50",
    duration: "1h 40m",
    price: 950,
    type: "Semi High-Speed",
    class: "CC",
    badge: "Fast",
    image:
      "https://i.ndtvimg.com/i/2016-03/gatimaan-express_650x400_51458676137.jpg",
  },
  {
    id: 6,
    name: "Howrah Rajdhani",
    trainNumber: "12301",
    from: "Delhi",
    to: "Kolkata",
    departure: "16:55",
    arrival: "10:00",
    duration: "17h 5m",
    price: 2600,
    type: "Superfast",
    class: "3A",
    badge: "Premium",
    image:
      "https://assets.thehansindia.com/h-upload/2021/11/09/1121045-special-trains.webp",
  },
  {
    id: 7,
    name: "Chennai Express",
    trainNumber: "12616",
    from: "New Delhi",
    to: "Chennai",
    departure: "20:10",
    arrival: "06:20",
    duration: "34h 10m",
    price: 2200,
    type: "Express",
    class: "3A",
    badge: "Popular",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROTMnSlCjAUVHaZ63_1k7oIjsc0k_ZnglAq_T99HlzvrBEmETHs7yS378&s=10",
  },
  {
    id: 8,
    name: "Lucknow Mail",
    trainNumber: "12230",
    from: "Lucknow",
    to: "Delhi",
    departure: "22:00",
    arrival: "07:00",
    duration: "9h",
    price: 1250,
    type: "Express",
    class: "3A",
    badge: "Popular",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/7/74/Lucknow_Mail.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=original",
  },
  {
    id: 9,
    name: "Deccan Queen",
    trainNumber: "12124",
    from: "Pune",
    to: "Mumbai",
    departure: "07:15",
    arrival: "10:25",
    duration: "3h 10m",
    price: 650,
    type: "Superfast",
    class: "CC",
    badge: "Popular",
    image:
      "https://www.team-bhp.com/sites/default/files/styles/amp_high_res/public/10%20Full.jpg",
  },
  {
    id: 10,
    name: "Karnataka Express",
    trainNumber: "12627",
    from: "Bengaluru",
    to: "Delhi",
    departure: "19:20",
    arrival: "10:30",
    duration: "39h 10m",
    price: 2100,
    type: "Express",
    class: "3A",
    badge: "Comfort",
    image: "https://live.staticflickr.com/4294/35653847350_6db7dcf816_h.jpg",
  },
];

// 4. BUS DATA

const buses = [
  {
    id: 1,
    name: "Volvo AC Sleeper",
    operator: "IntrCity SmartBus",
    from: "Delhi",
    to: "Jaipur",
    departure: "22:00",
    arrival: "05:00",
    duration: "7h",
    price: 850,
    type: "AC Sleeper",
    seatsAvailable: 12,
    badge: "Popular",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCvsZn7EVrPh-799rdzzbomMuFeF7hPAuQFhi8FvzkRA&s",
  },
  {
    id: 2,
    name: "Premium AC Seater",
    operator: "Zingbus",
    from: "Delhi",
    to: "Manali",
    departure: "19:30",
    arrival: "08:30",
    duration: "13h",
    price: 1450,
    type: "AC Sleeper",
    seatsAvailable: 8,
    badge: "Comfort",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxsMfteyZfTQSuA3q4cYa9uZ-7dJg5zwTy17MU3UomXy3zwzH_0nr9cdo&s=10",
  },
  {
    id: 3,
    name: "Luxury Volvo",
    operator: "HRTC",
    from: "Shimla",
    to: "Delhi",
    departure: "20:00",
    arrival: "06:30",
    duration: "10h 30m",
    price: 1100,
    type: "AC Seater",
    seatsAvailable: 15,
    badge: "Popular",
    image:
      "https://hrtchub.com/wp-content/uploads/al_opt_content/IMAGE/hrtchub.com/wp-content/uploads/2024/10/BUs_2-1024x592.png.bv_resized_mobile.png.bv.webp?bv_host=hrtchub.com",
  },
  {
    id: 4,
    name: "AC Sleeper Coach",
    operator: "RedBus Travels",
    from: "Mumbai",
    to: "Goa",
    departure: "21:00",
    arrival: "08:00",
    duration: "11h",
    price: 1250,
    type: "AC Sleeper",
    seatsAvailable: 10,
    badge: "Best Price",
    image:
      "https://content.jdmagicbox.com/quickquotes/images_main/luxury-coach-bus-802824038-edhwygt6.jpg?impolicy=queryparam&im=Resize=(360,360),aspect=fit",
  },
  {
    id: 5,
    name: "Volvo Multi-Axle",
    operator: "KSRTC",
    from: "Bengaluru",
    to: "Chennai",
    departure: "23:00",
    arrival: "06:00",
    duration: "7h",
    price: 950,
    type: "AC Sleeper",
    seatsAvailable: 18,
    badge: "Popular",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzUIocw8n7QCzyYg3vmFt_-eRCqKBoKV2dt9tfZJ-wx7qohc0veMgu75jf&s=10",
  },
  {
    id: 6,
    name: "Premium Sleeper",
    operator: "IntrCity SmartBus",
    from: "Lucknow",
    to: "Delhi",
    departure: "21:30",
    arrival: "07:00",
    duration: "9h 30m",
    price: 1050,
    type: "AC Sleeper",
    seatsAvailable: 9,
    badge: "Comfort",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjdxNP7J28sH2sd8O0xbDT3bsHV4F38-hawT6VD8P4Jw&s=10",
  },
  {
    id: 7,
    name: "AC Seater",
    operator: "UPSRTC",
    from: "Kanpur",
    to: "Lucknow",
    departure: "08:00",
    arrival: "10:00",
    duration: "2h",
    price: 250,
    type: "AC Seater",
    seatsAvailable: 25,
    badge: "Budget",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcbm6xiy8pPQ1_g5IVgxup5OV89dUdCLMlfErGTSpYgppEI5p525bPzVCK&s=10",
  },
  {
    id: 8,
    name: "Luxury Sleeper",
    operator: "VRL Travels",
    from: "Hyderabad",
    to: "Bengaluru",
    departure: "20:30",
    arrival: "07:30",
    duration: "11h",
    price: 1350,
    type: "AC Sleeper",
    seatsAvailable: 11,
    badge: "Premium",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfIgT7QCSqycmv_GulqwoYmu5xU8XZSiFgHinGNl8q_L8Z1Q_A9YyZeL_k&s=10",
  },
  {
    id: 9,
    name: "Volvo AC Bus",
    operator: "RSRTC",
    from: "Jaipur",
    to: "Udaipur",
    departure: "07:00",
    arrival: "13:30",
    duration: "6h 30m",
    price: 700,
    type: "AC Seater",
    seatsAvailable: 20,
    badge: "Popular",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMAqZXjxlERiRTzaVycgMGluruXX1IRBFH7kOfFY1rKP02nOrJw-WaYw4&s=10",
  },
  {
    id: 10,
    name: "Premium AC Sleeper",
    operator: "Orange Travels",
    from: "Pune",
    to: "Goa",
    departure: "21:00",
    arrival: "08:00",
    duration: "11h",
    price: 1150,
    type: "AC Sleeper",
    seatsAvailable: 7,
    badge: "Comfort",
    image:
      "https://image.made-in-china.com/202f0j00eCzRYLdyHuka/VIP-Luxury-Leather-35-55-Seat-Bus-with-Certificate.webp",
  },
];

window.TripEaseBookingData = {
  hotels,
  flights,
  trains,
  buses,
};
